services:

  postgres:
    image: postgres:17.0-alpine3.20
    container_name: mypostgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${ORDER_DB}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./spotService/migrations/db_spot:/docker-entrypoint-initdb.d:ro
    healthcheck:
      test:
        [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${ORDER_DB} && pg_isready -U ${POSTGRES_USER} -d ${SPOT_DB}" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped
    networks:
      - microservices-net

  redis:
    image: redis:7.2.5-alpine3.20
    container_name: myredis
    ports:
      - "${EXTERNAL_REDIS_PORT}:6379"
    command: [ "redis-server", "--save", "", "--appendonly", "no", "--maxmemory-policy", "allkeys-lru" ]
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s
    restart: unless-stopped
    networks:
      - microservices-net

  otel-collector:
    image: otel/opentelemetry-collector-contrib:0.147.0
    container_name: otel-collector
    command: [ "--config=/etc/otel_collector_config.yaml" ]
    volumes:
      - ./shared/infrastructure/otel/otel_collector_config.yaml:/etc/otel_collector_config.yaml
    ports:
      - "${OTEL_GRPC_PORT}:4317"
      - "${OTEL_HTTP_PORT}:4318"
      - "${OTEL_ZPAGES_PORT}:8889"
      - "${OTEL_HEALTH_PORT}:13133"
    healthcheck:
      test: [ "CMD", "wget", "--quiet", "--spider", "http://localhost:13133/health" ]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 20s
    depends_on:
      jaeger:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - microservices-net

  jaeger:
    image: jaegertracing/all-in-one:1.62.0
    container_name: jaeger
    environment:
      - COLLECTOR_OTLP_ENABLED=true
      - SPAN_STORAGE_TYPE=memory
      - MEMORY_MAX_TRACES=50000
    ports:
      - "${JAEGER_UI_PORT}:16686"
    healthcheck:
      test: [ "CMD", "wget", "--spider", "-q", "http://localhost:16686" ]
      interval: 5s
      timeout: 3s
      retries: 5
      start_period: 10s
    restart: unless-stopped
    networks:
      - microservices-net

networks:
  microservices-net:
    name: microservices-net
    driver: bridge

volumes:
  pgdata:
