version: '3'

tasks:
  test:
    desc: Запустить все юнит тесты
    cmds:
      - echo "{{.BLUE}}Запуск всех тестов...{{.NC}}"
      - go test ./orderService/... ./spotService/... -v

  test:short:
    desc: Запустить все юнит тесты (краткий вывод)
    cmds:
      - echo "{{.BLUE}}Запуск всех тестов...{{.NC}}"
      - go test ./orderService/... ./spotService/...

  test:race:
    desc: Запустить юнит тесты с проверкой race conditions
    cmds:
      - echo "{{.BLUE}}Проверка race conditions...{{.NC}}"
      - go test -race ./orderService/... ./spotService/...

  test:integration:
    desc: Запустить интеграционные тесты (требуется Docker)
    cmds:
      - echo "{{.BLUE}}Проверка Docker...{{.NC}}"
      - cmd: docker info > /dev/null 2>&1 || (echo "Docker не запущен" && exit 1)
        platforms: [ linux, darwin ]
      - cmd: docker info > nul 2>&1 || (echo "Docker не запущен" && exit 1)
        platforms: [ windows ]
      - echo "{{.BLUE}}Запуск интеграционных тестов...{{.NC}}"
      - go test -tags=integration ./orderService/tests/... -v -timeout 10m -count=1
      - go test -tags=integration ./spotService/tests/... -v -timeout 5m -count=1
      - echo "{{.GREEN}}Интеграционные тесты завершены{{.NC}}"

  test:integration:race:
    desc: Запустить интеграционные тесты с проверкой race conditions (требуется Docker)
    cmds:
      - echo "{{.BLUE}}Проверка Docker...{{.NC}}"
      - cmd: docker info > /dev/null 2>&1 || (echo "Docker не запущен" && exit 1)
        platforms: [ linux, darwin ]
      - cmd: docker info > nul 2>&1 || (echo "Docker не запущен" && exit 1)
        platforms: [ windows ]
      - echo "{{.BLUE}}Запуск интеграционных тестов...{{.NC}}"
      - go test -tags=integration -race ./orderService/tests/... -v -timeout 10m -count=1
      - go test -tags=integration -race ./spotService/tests/... -v -timeout 5m -count=1
      - echo "{{.GREEN}}Интеграционные тесты завершены{{.NC}}"

  test:all:
    desc: Прогнать все тесты (юнит + интеграционные, требуется Docker для integration)
    cmds:
      - echo "{{.BLUE}}Запуск юнит тестов...{{.NC}}"
      - go test ./orderService/... ./spotService/... -v -count=1

      - echo "{{.BLUE}}Проверка Docker...{{.NC}}"
      - cmd: docker info > /dev/null 2>&1 || (echo "Docker не запущен" && exit 1)
        platforms: [ linux, darwin ]
      - cmd: docker info > nul 2>&1 || (echo "Docker не запущен" && exit 1)
        platforms: [ windows ]

      - echo "{{.BLUE}}Запуск интеграционных тестов...{{.NC}}"
      - go test -tags=integration ./orderService/tests/... -v -timeout 10m -count=1
      - go test -tags=integration ./spotService/tests/... -v -timeout 5m -count=1

      - echo "{{.GREEN}}Все тесты завершены{{.NC}}"

  test:all:race:
    desc: Прогнать все тесты с race (юнит + интеграционные, требуется Docker для integration)
    cmds:
      - echo "{{.BLUE}}Запуск юнит тестов (race)...{{.NC}}"
      - go test -race ./orderService/... ./spotService/... -v -count=1

      - echo "{{.BLUE}}Проверка Docker...{{.NC}}"
      - cmd: docker info > /dev/null 2>&1 || (echo "Docker не запущен" && exit 1)
        platforms: [ linux, darwin ]
      - cmd: docker info > nul 2>&1 || (echo "Docker не запущен" && exit 1)
        platforms: [ windows ]

      - echo "{{.BLUE}}Запуск интеграционных тестов (race)...{{.NC}}"
      - go test -tags=integration -race ./orderService/tests/... -v -timeout 10m -count=1
      - go test -tags=integration -race ./spotService/tests/... -v -timeout m -count=1

      - echo "{{.GREEN}}Все тесты (race) завершены{{.NC}}"

  lint:
    # TODO: добавить линтер

  mocks:generate:
    desc: Сгенерировать моки с помощью mockery
    cmds:
      - echo "{{.BLUE}}Генерация моков...{{.NC}}"
      - cmd: which mockery
        platforms: [linux, darwin]
        ignore_error: true
      - cmd: where mockery
        platforms: [windows]
        ignore_error: true
      - mockery --all --dir=./orderService/internal/services/order --output=./orderService/internal/services/mocks --case=underscore
      - mockery --all --dir=./spotService/internal/services/spot --output=./spotService/internal/services/mocks --case=underscore

      - mockery --all --dir=./orderService/internal/grpc/order --output=./orderService/internal/grpc/mocks --case=underscore
      - mockery --all --dir=./spotService/internal/grpc/spot --output=./spotService/internal/grpc/mocks --case=underscore

      - echo "{{.GREEN}}Моки успешно сгенерированы{{.NC}}"

  clean:
    desc: Очистить сгенерированные файлы
    cmds:
      - echo "{{.BLUE}}Очистка...{{.NC}}"
      - cmd: rm -f coverage*.out coverage*.html
        platforms: [linux, darwin]
      - cmd: del /f /q coverage*.out coverage*.html 2>nul || echo.
        platforms: [windows]
      - echo "{{.GREEN}}Очистка завершена{{.NC}}"

  clean:cache:
    desc: Очистить кэш тестов
    cmds:
      - echo "{{.BLUE}}Очистка кэша тестов...{{.NC}}"
      - go clean -testcache
      - echo "{{.GREEN}}Кэш очищен{{.NC}}"
