// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	"github.com/nastyazhadan/spot-order-grpc/orderService/internal/domain/models/shared"
	mock "github.com/stretchr/testify/mock"

	sharedmodels "github.com/nastyazhadan/spot-order-grpc/shared/models"

	uuid "github.com/google/uuid"
)

// OrderService is an autogenerated mock type for the OrderService type
type OrderService struct {
	mock.Mock
}

// CreateOrder provides a mock function with given fields: ctx, userID, marketID, orderType, price, quantity
func (_m *OrderService) CreateOrder(ctx context.Context, userID uuid.UUID, marketID uuid.UUID, orderType shared.OrderType, price sharedmodels.Decimal, quantity int64) (uuid.UUID, shared.OrderStatus, error) {
	ret := _m.Called(ctx, userID, marketID, orderType, price, quantity)

	if len(ret) == 0 {
		panic("no return value specified for CreateOrder")
	}

	var r0 uuid.UUID
	var r1 shared.OrderStatus
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, shared.OrderType, sharedmodels.Decimal, int64) (uuid.UUID, shared.OrderStatus, error)); ok {
		return rf(ctx, userID, marketID, orderType, price, quantity)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, shared.OrderType, sharedmodels.Decimal, int64) uuid.UUID); ok {
		r0 = rf(ctx, userID, marketID, orderType, price, quantity)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(uuid.UUID)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID, shared.OrderType, sharedmodels.Decimal, int64) shared.OrderStatus); ok {
		r1 = rf(ctx, userID, marketID, orderType, price, quantity)
	} else {
		r1 = ret.Get(1).(shared.OrderStatus)
	}

	if rf, ok := ret.Get(2).(func(context.Context, uuid.UUID, uuid.UUID, shared.OrderType, sharedmodels.Decimal, int64) error); ok {
		r2 = rf(ctx, userID, marketID, orderType, price, quantity)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// GetOrderStatus provides a mock function with given fields: ctx, orderId, userID
func (_m *OrderService) GetOrderStatus(ctx context.Context, orderId uuid.UUID, userID uuid.UUID) (shared.OrderStatus, error) {
	ret := _m.Called(ctx, orderId, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetOrderStatus")
	}

	var r0 shared.OrderStatus
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) (shared.OrderStatus, error)); ok {
		return rf(ctx, orderId, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) shared.OrderStatus); ok {
		r0 = rf(ctx, orderId, userID)
	} else {
		r0 = ret.Get(0).(shared.OrderStatus)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r1 = rf(ctx, orderId, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewOrderService creates a new instance of OrderService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewOrderService(t interface {
	mock.TestingT
	Cleanup(func())
}) *OrderService {
	mock := &OrderService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
