// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	models "github.com/nastyazhadan/spot-order-grpc/spotService/internal/domain/models"
	mock "github.com/stretchr/testify/mock"
)

// CursorStore is an autogenerated mock type for the CursorStore type
type CursorStore struct {
	mock.Mock
}

// Get provides a mock function with given fields: ctx, pollerName
func (_m *CursorStore) Get(ctx context.Context, pollerName string) (models.PollerCursor, error) {
	ret := _m.Called(ctx, pollerName)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 models.PollerCursor
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (models.PollerCursor, error)); ok {
		return rf(ctx, pollerName)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) models.PollerCursor); ok {
		r0 = rf(ctx, pollerName)
	} else {
		r0 = ret.Get(0).(models.PollerCursor)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, pollerName)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewCursorStore creates a new instance of CursorStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCursorStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *CursorStore {
	mock := &CursorStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
