// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// MarketCacheRefresher is an autogenerated mock type for the MarketCacheRefresher type
type MarketCacheRefresher struct {
	mock.Mock
}

// InvalidateByIDs provides a mock function with given fields: ctx, ids
func (_m *MarketCacheRefresher) InvalidateByIDs(ctx context.Context, ids []uuid.UUID) error {
	ret := _m.Called(ctx, ids)

	if len(ret) == 0 {
		panic("no return value specified for InvalidateByIDs")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, []uuid.UUID) error); ok {
		r0 = rf(ctx, ids)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// RefreshAll provides a mock function with given fields: ctx
func (_m *MarketCacheRefresher) RefreshAll(ctx context.Context) error {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for RefreshAll")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewMarketCacheRefresher creates a new instance of MarketCacheRefresher. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMarketCacheRefresher(t interface {
	mock.TestingT
	Cleanup(func())
}) *MarketCacheRefresher {
	mock := &MarketCacheRefresher{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
