// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	models "github.com/nastyazhadan/spot-order-grpc/shared/models"
	mock "github.com/stretchr/testify/mock"

	time "time"

	uuid "github.com/google/uuid"
)

// MarketReader is an autogenerated mock type for the MarketReader type
type MarketReader struct {
	mock.Mock
}

// ListUpdatedSince provides a mock function with given fields: ctx, since, afterID, limit
func (_m *MarketReader) ListUpdatedSince(ctx context.Context, since time.Time, afterID uuid.UUID, limit int) ([]models.Market, error) {
	ret := _m.Called(ctx, since, afterID, limit)

	if len(ret) == 0 {
		panic("no return value specified for ListUpdatedSince")
	}

	var r0 []models.Market
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, time.Time, uuid.UUID, int) ([]models.Market, error)); ok {
		return rf(ctx, since, afterID, limit)
	}
	if rf, ok := ret.Get(0).(func(context.Context, time.Time, uuid.UUID, int) []models.Market); ok {
		r0 = rf(ctx, since, afterID, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.Market)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, time.Time, uuid.UUID, int) error); ok {
		r1 = rf(ctx, since, afterID, limit)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewMarketReader creates a new instance of MarketReader. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMarketReader(t interface {
	mock.TestingT
	Cleanup(func())
}) *MarketReader {
	mock := &MarketReader{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
