// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	models "github.com/nastyazhadan/spot-order-grpc/shared/models"
	mock "github.com/stretchr/testify/mock"

	time "time"

	uuid "github.com/google/uuid"
)

// MarketByIDCacheRepository is an autogenerated mock type for the MarketByIDCacheRepository type
type MarketByIDCacheRepository struct {
	mock.Mock
}

// DeleteMarketByID provides a mock function with given fields: ctx, id
func (_m *MarketByIDCacheRepository) DeleteMarketByID(ctx context.Context, id uuid.UUID) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteMarketByID")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetMarketByID provides a mock function with given fields: ctx, id
func (_m *MarketByIDCacheRepository) GetMarketByID(ctx context.Context, id uuid.UUID) (models.Market, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetMarketByID")
	}

	var r0 models.Market
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (models.Market, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) models.Market); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(models.Market)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SetMarketByID provides a mock function with given fields: ctx, market, ttl
func (_m *MarketByIDCacheRepository) SetMarketByID(ctx context.Context, market models.Market, ttl time.Duration) error {
	ret := _m.Called(ctx, market, ttl)

	if len(ret) == 0 {
		panic("no return value specified for SetMarketByID")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, models.Market, time.Duration) error); ok {
		r0 = rf(ctx, market, ttl)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewMarketByIDCacheRepository creates a new instance of MarketByIDCacheRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMarketByIDCacheRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MarketByIDCacheRepository {
	mock := &MarketByIDCacheRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
