// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	models "github.com/nastyazhadan/spot-order-grpc/shared/models"
	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// MarketRepository is an autogenerated mock type for the MarketRepository type
type MarketRepository struct {
	mock.Mock
}

// GetMarketByID provides a mock function with given fields: ctx, id
func (_m *MarketRepository) GetMarketByID(ctx context.Context, id uuid.UUID) (models.Market, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetMarketByID")
	}

	var r0 models.Market
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (models.Market, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) models.Market); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(models.Market)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetMarketsPage provides a mock function with given fields: ctx, roleKey, limit, offset
func (_m *MarketRepository) GetMarketsPage(ctx context.Context, roleKey string, limit uint64, offset uint64) ([]models.Market, error) {
	ret := _m.Called(ctx, roleKey, limit, offset)

	if len(ret) == 0 {
		panic("no return value specified for GetMarketsPage")
	}

	var r0 []models.Market
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, uint64, uint64) ([]models.Market, error)); ok {
		return rf(ctx, roleKey, limit, offset)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, uint64, uint64) []models.Market); ok {
		r0 = rf(ctx, roleKey, limit, offset)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.Market)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, uint64, uint64) error); ok {
		r1 = rf(ctx, roleKey, limit, offset)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewMarketRepository creates a new instance of MarketRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMarketRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MarketRepository {
	mock := &MarketRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
