// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	domainmodels "github.com/nastyazhadan/spot-order-grpc/spotService/internal/domain/models"
	mock "github.com/stretchr/testify/mock"

	models "github.com/nastyazhadan/spot-order-grpc/shared/models"
)

// MarketEventProducer is an autogenerated mock type for the MarketEventProducer type
type MarketEventProducer struct {
	mock.Mock
}

// ProduceMarketStateChangedBatch provides a mock function with given fields: ctx, events, cursor
func (_m *MarketEventProducer) ProduceMarketStateChangedBatch(ctx context.Context, events []models.MarketStateChangedEvent, cursor domainmodels.PollerCursor) error {
	ret := _m.Called(ctx, events, cursor)

	if len(ret) == 0 {
		panic("no return value specified for PublishMarketStateChanged")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, []models.MarketStateChangedEvent, domainmodels.PollerCursor) error); ok {
		r0 = rf(ctx, events, cursor)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewMarketEventProducer creates a new instance of MarketEventProducer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMarketEventProducer(t interface {
	mock.TestingT
	Cleanup(func())
}) *MarketEventProducer {
	mock := &MarketEventProducer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
