// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	models "github.com/nastyazhadan/spot-order-grpc/shared/models"
	mock "github.com/stretchr/testify/mock"

	time "time"
)

// MarketCacheRepository is an autogenerated mock type for the MarketCacheRepository type
type MarketCacheRepository struct {
	mock.Mock
}

// DeleteMarkets provides a mock function with given fields: ctx, roleKey
func (_m *MarketCacheRepository) DeleteMarkets(ctx context.Context, roleKey string) error {
	ret := _m.Called(ctx, roleKey)

	if len(ret) == 0 {
		panic("no return value specified for DeleteMarkets")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, roleKey)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetMarkets provides a mock function with given fields: ctx, roleKey
func (_m *MarketCacheRepository) GetMarkets(ctx context.Context, roleKey string) ([]models.Market, error) {
	ret := _m.Called(ctx, roleKey)

	if len(ret) == 0 {
		panic("no return value specified for GetMarkets")
	}

	var r0 []models.Market
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]models.Market, error)); ok {
		return rf(ctx, roleKey)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []models.Market); ok {
		r0 = rf(ctx, roleKey)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.Market)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, roleKey)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SetMarkets provides a mock function with given fields: ctx, market, roleKey, ttl
func (_m *MarketCacheRepository) SetMarkets(ctx context.Context, market []models.Market, roleKey string, ttl time.Duration) error {
	ret := _m.Called(ctx, market, roleKey, ttl)

	if len(ret) == 0 {
		panic("no return value specified for SetMarkets")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, []models.Market, string, time.Duration) error); ok {
		r0 = rf(ctx, market, roleKey, ttl)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewMarketCacheRepository creates a new instance of MarketCacheRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMarketCacheRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MarketCacheRepository {
	mock := &MarketCacheRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
