// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	models "github.com/nastyazhadan/spot-order-grpc/shared/models"
	mock "github.com/stretchr/testify/mock"
)

// MarketRepository is an autogenerated mock type for the MarketRepository type
type MarketRepository struct {
	mock.Mock
}

// ListAll provides a mock function with given fields: ctx
func (_m *MarketRepository) ListAll(ctx context.Context) ([]models.Market, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for ListAll")
	}

	var r0 []models.Market
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]models.Market, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []models.Market); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.Market)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewMarketRepository creates a new instance of MarketRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMarketRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MarketRepository {
	mock := &MarketRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
