// Package mocks Code generated by mockery. DO NOT EDIT.
package mocks

import (
	"context"

	"github.com/nastyazhadan/spot-order-grpc/shared/models"
	"github.com/stretchr/testify/mock"
)

type MockSpotMarketViewer struct {
	mock.Mock
}

func (m *MockSpotMarketViewer) ListAll(ctx context.Context) ([]models.Market, error) {
	args := m.Called(ctx)
	if args.Get(0) == nil {
		return nil, args.Error(1)
	}
	return args.Get(0).([]models.Market), args.Error(1)
}
