version: "3"

tasks:
  generate:
    aliases:
      - fx
    desc: "Generate code from proto files"
    cmds:
      - protoc -I proto -I lib proto/order/v1/*.proto --go_out=./fx/go --go_opt=paths=source_relative --go-grpc_out=./fx/go --go-grpc_opt=paths=source_relative
      - protoc -I proto -I lib proto/spot/v1/*.proto --go_out=./fx/go --go_opt=paths=source_relative --go-grpc_out=./fx/go --go-grpc_opt=paths=source_relative
      - protoc -I proto -I lib proto/auth/v1/*.proto --go_out=./fx/go --go_opt=paths=source_relative --go-grpc_out=./fx/go --go-grpc_opt=paths=source_relative
      - protoc -I proto -I lib proto/events/v1/*.proto --go_out=./fx/go --go_opt=paths=source_relative --go-grpc_out=./fx/go --go-grpc_opt=paths=source_relative