// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	models "github.com/nastyazhadan/spot-order-grpc/shared/models"
	mock "github.com/stretchr/testify/mock"
)

// SpotInstrument is an autogenerated mock type for the SpotInstrument type
type SpotInstrument struct {
	mock.Mock
}

// ViewMarkets provides a mock function with given fields: ctx, userRoles
func (_m *SpotInstrument) ViewMarkets(ctx context.Context, userRoles []models.UserRole) ([]models.Market, error) {
	ret := _m.Called(ctx, userRoles)

	if len(ret) == 0 {
		panic("no return value specified for ViewMarkets")
	}

	var r0 []models.Market
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, []models.UserRole) ([]models.Market, error)); ok {
		return rf(ctx, userRoles)
	}
	if rf, ok := ret.Get(0).(func(context.Context, []models.UserRole) []models.Market); ok {
		r0 = rf(ctx, userRoles)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.Market)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, []models.UserRole) error); ok {
		r1 = rf(ctx, userRoles)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewSpotInstrument creates a new instance of SpotInstrument. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewSpotInstrument(t interface {
	mock.TestingT
	Cleanup(func())
}) *SpotInstrument {
	mock := &SpotInstrument{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
