// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	models "github.com/nastyazhadan/spot-order-grpc/orderService/internal/domain/models"
	mock "github.com/stretchr/testify/mock"

	shared "github.com/nastyazhadan/spot-order-grpc/orderService/internal/domain/models/shared"

	time "time"

	uuid "github.com/google/uuid"
)

// Getter is an autogenerated mock type for the Getter type
type Getter struct {
	mock.Mock
}

// FindOrderForIdempotencyRecovery provides a mock function with given fields: ctx, userID, marketID, orderType, price, quantity, startedAt
func (_m *Getter) FindOrderForIdempotencyRecovery(ctx context.Context, userID uuid.UUID, marketID uuid.UUID, orderType shared.OrderType, price shared.Decimal, quantity int64, startedAt time.Time) (models.Order, error) {
	ret := _m.Called(ctx, userID, marketID, orderType, price, quantity, startedAt)

	if len(ret) == 0 {
		panic("no return value specified for FindOrderForIdempotencyRecovery")
	}

	var r0 models.Order
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, shared.OrderType, shared.Decimal, int64, time.Time) (models.Order, error)); ok {
		return rf(ctx, userID, marketID, orderType, price, quantity, startedAt)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, shared.OrderType, shared.Decimal, int64, time.Time) models.Order); ok {
		r0 = rf(ctx, userID, marketID, orderType, price, quantity, startedAt)
	} else {
		r0 = ret.Get(0).(models.Order)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID, shared.OrderType, shared.Decimal, int64, time.Time) error); ok {
		r1 = rf(ctx, userID, marketID, orderType, price, quantity, startedAt)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetOrder provides a mock function with given fields: ctx, id, userID
func (_m *Getter) GetOrder(ctx context.Context, id uuid.UUID, userID uuid.UUID) (models.Order, error) {
	ret := _m.Called(ctx, id, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetOrder")
	}

	var r0 models.Order
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) (models.Order, error)); ok {
		return rf(ctx, id, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) models.Order); ok {
		r0 = rf(ctx, id, userID)
	} else {
		r0 = ret.Get(0).(models.Order)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r1 = rf(ctx, id, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewGetter creates a new instance of Getter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewGetter(t interface {
	mock.TestingT
	Cleanup(func())
}) *Getter {
	mock := &Getter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
