// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	time "time"

	uuid "github.com/google/uuid"
)

// MarketBlockStore is an autogenerated mock type for the MarketBlockStore type
type MarketBlockStore struct {
	mock.Mock
}

// IsBlocked provides a mock function with given fields: ctx, marketID
func (_m *MarketBlockStore) IsBlocked(ctx context.Context, marketID uuid.UUID) (bool, error) {
	ret := _m.Called(ctx, marketID)

	if len(ret) == 0 {
		panic("no return value specified for IsBlocked")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (bool, error)); ok {
		return rf(ctx, marketID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) bool); ok {
		r0 = rf(ctx, marketID)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, marketID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SynchronizeState provides a mock function with given fields: ctx, marketID, blocked, updatedAt
func (_m *MarketBlockStore) SynchronizeState(ctx context.Context, marketID uuid.UUID, blocked bool, updatedAt time.Time) (bool, error) {
	ret := _m.Called(ctx, marketID, blocked, updatedAt)

	if len(ret) == 0 {
		panic("no return value specified for SynchronizeState")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, bool, time.Time) (bool, error)); ok {
		return rf(ctx, marketID, blocked, updatedAt)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, bool, time.Time) bool); ok {
		r0 = rf(ctx, marketID, blocked, updatedAt)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, bool, time.Time) error); ok {
		r1 = rf(ctx, marketID, blocked, updatedAt)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewMarketBlockStore creates a new instance of MarketBlockStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMarketBlockStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *MarketBlockStore {
	mock := &MarketBlockStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
