// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	models "github.com/nastyazhadan/spot-order-grpc/shared/models"
	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// MarketViewer is an autogenerated mock type for the MarketViewer type
type MarketViewer struct {
	mock.Mock
}

// GetMarketByID provides a mock function with given fields: ctx, id
func (_m *MarketViewer) GetMarketByID(ctx context.Context, id uuid.UUID) (models.Market, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetMarketByID")
	}

	var r0 models.Market
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (models.Market, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) models.Market); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(models.Market)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewMarketViewer creates a new instance of MarketViewer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMarketViewer(t interface {
	mock.TestingT
	Cleanup(func())
}) *MarketViewer {
	mock := &MarketViewer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
