// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	models "github.com/nastyazhadan/spot-order-grpc/orderService/internal/domain/models"
	mock "github.com/stretchr/testify/mock"

	pgx "github.com/jackc/pgx/v5"

	uuid "github.com/google/uuid"
)

// MarketInboxWriter is an autogenerated mock type for the MarketInboxWriter type
type MarketInboxWriter struct {
	mock.Mock
}

// BeginProcessing provides a mock function with given fields: ctx, transaction, event
func (_m *MarketInboxWriter) BeginProcessing(ctx context.Context, transaction pgx.Tx, event models.InboxEvent) (bool, models.InboxEventStatus, error) {
	ret := _m.Called(ctx, transaction, event)

	if len(ret) == 0 {
		panic("no return value specified for BeginProcessing")
	}

	var r0 bool
	var r1 models.InboxEventStatus
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, pgx.Tx, models.InboxEvent) (bool, models.InboxEventStatus, error)); ok {
		return rf(ctx, transaction, event)
	}
	if rf, ok := ret.Get(0).(func(context.Context, pgx.Tx, models.InboxEvent) bool); ok {
		r0 = rf(ctx, transaction, event)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, pgx.Tx, models.InboxEvent) models.InboxEventStatus); ok {
		r1 = rf(ctx, transaction, event)
	} else {
		r1 = ret.Get(1).(models.InboxEventStatus)
	}

	if rf, ok := ret.Get(2).(func(context.Context, pgx.Tx, models.InboxEvent) error); ok {
		r2 = rf(ctx, transaction, event)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MarkProcessed provides a mock function with given fields: ctx, transaction, eventID, consumerGroup
func (_m *MarketInboxWriter) MarkProcessed(ctx context.Context, transaction pgx.Tx, eventID uuid.UUID, consumerGroup string) error {
	ret := _m.Called(ctx, transaction, eventID, consumerGroup)

	if len(ret) == 0 {
		panic("no return value specified for MarkProcessed")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, pgx.Tx, uuid.UUID, string) error); ok {
		r0 = rf(ctx, transaction, eventID, consumerGroup)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SaveFailed provides a mock function with given fields: ctx, event, errText
func (_m *MarketInboxWriter) SaveFailed(ctx context.Context, event models.InboxEvent, errText string) error {
	ret := _m.Called(ctx, event, errText)

	if len(ret) == 0 {
		panic("no return value specified for SaveFailed")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, models.InboxEvent, string) error); ok {
		r0 = rf(ctx, event, errText)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewMarketInboxWriter creates a new instance of MarketInboxWriter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMarketInboxWriter(t interface {
	mock.TestingT
	Cleanup(func())
}) *MarketInboxWriter {
	mock := &MarketInboxWriter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
