// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	models "github.com/nastyazhadan/spot-order-grpc/shared/models"
	mock "github.com/stretchr/testify/mock"
)

// MarketViewer is an autogenerated mock type for the MarketViewer type
type MarketViewer struct {
	mock.Mock
}

// ViewMarkets provides a mock function with given fields: ctx, roles
func (_m *MarketViewer) ViewMarkets(ctx context.Context, roles []models.UserRole) ([]models.Market, error) {
	ret := _m.Called(ctx, roles)

	if len(ret) == 0 {
		panic("no return value specified for ViewMarkets")
	}

	var r0 []models.Market
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, []models.UserRole) ([]models.Market, error)); ok {
		return rf(ctx, roles)
	}
	if rf, ok := ret.Get(0).(func(context.Context, []models.UserRole) []models.Market); ok {
		r0 = rf(ctx, roles)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.Market)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, []models.UserRole) error); ok {
		r1 = rf(ctx, roles)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewMarketViewer creates a new instance of MarketViewer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMarketViewer(t interface {
	mock.TestingT
	Cleanup(func())
}) *MarketViewer {
	mock := &MarketViewer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
