// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	pgx "github.com/jackc/pgx/v5"

	uuid "github.com/google/uuid"
)

// MarketOrderCanceler is an autogenerated mock type for the MarketOrderCanceler type
type MarketOrderCanceler struct {
	mock.Mock
}

// CancelActiveOrdersByMarket provides a mock function with given fields: ctx, transaction, marketID
func (_m *MarketOrderCanceler) CancelActiveOrdersByMarket(ctx context.Context, transaction pgx.Tx, marketID uuid.UUID) ([]uuid.UUID, error) {
	ret := _m.Called(ctx, transaction, marketID)

	if len(ret) == 0 {
		panic("no return value specified for CancelActiveOrdersByMarket")
	}

	var r0 []uuid.UUID
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, pgx.Tx, uuid.UUID) ([]uuid.UUID, error)); ok {
		return rf(ctx, transaction, marketID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, pgx.Tx, uuid.UUID) []uuid.UUID); ok {
		r0 = rf(ctx, transaction, marketID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]uuid.UUID)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, pgx.Tx, uuid.UUID) error); ok {
		r1 = rf(ctx, transaction, marketID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewMarketOrderCanceler creates a new instance of MarketOrderCanceler. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMarketOrderCanceler(t interface {
	mock.TestingT
	Cleanup(func())
}) *MarketOrderCanceler {
	mock := &MarketOrderCanceler{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
