// Package mocks Code generated by mockery. DO NOT EDIT.
package mocks

import (
	"context"

	"github.com/google/uuid"
	"github.com/nastyazhadan/spot-order-grpc/orderService/internal/domain/models"
	"github.com/stretchr/testify/mock"
)

type MockGetter struct {
	mock.Mock
}

func (m *MockGetter) GetOrder(ctx context.Context, id uuid.UUID) (models.Order, error) {
	args := m.Called(ctx, id)
	if args.Get(0) == nil {
		return models.Order{}, args.Error(1)
	}
	return args.Get(0).(models.Order), args.Error(1)
}
