// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	models "github.com/nastyazhadan/spot-order-grpc/orderService/internal/domain/models"
	mock "github.com/stretchr/testify/mock"

	pgx "github.com/jackc/pgx/v5"
)

// OrderEventProducer is an autogenerated mock type for the OrderEventProducer type
type OrderEventProducer struct {
	mock.Mock
}

// ProduceOrderStatusUpdated provides a mock function with given fields: ctx, transaction, event
func (_m *OrderEventProducer) ProduceOrderStatusUpdated(ctx context.Context, transaction pgx.Tx, event models.OrderStatusUpdatedEvent) error {
	ret := _m.Called(ctx, transaction, event)

	if len(ret) == 0 {
		panic("no return value specified for ProduceOrderStatusUpdated")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, pgx.Tx, models.OrderStatusUpdatedEvent) error); ok {
		r0 = rf(ctx, transaction, event)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewOrderEventProducer creates a new instance of OrderEventProducer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewOrderEventProducer(t interface {
	mock.TestingT
	Cleanup(func())
}) *OrderEventProducer {
	mock := &OrderEventProducer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
