// Package mocks Code generated by mockery. DO NOT EDIT.
package mocks

import (
	"context"

	"github.com/nastyazhadan/spot-order-grpc/orderService/internal/domain/models"
	"github.com/stretchr/testify/mock"
)

type MockSaver struct {
	mock.Mock
}

func (m *MockSaver) SaveOrder(ctx context.Context, order models.Order) error {
	args := m.Called(ctx, order)
	return args.Error(0)
}
