receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
        max_recv_msg_size_mib: 64
        read_buffer_size: 512_000

processors:
  batch:
    send_batch_size: 1000
    timeout: 10s
    send_batch_max_size: 1000

  memory_limiter:
    check_interval: 1s
    limit_percentage: 75
    spike_limit_percentage: 15

  resourcedetection:
    detectors: [env, system]
    timeout: 5s

  probabilistic_sampler:
    sampling_percentage: 100

exporters:
  otlp_grpc/tempo:
    endpoint: tempo:4317
    tls:
      insecure: true

  debug:
    verbosity: detailed

extensions:
  health_check:
    endpoint: 0.0.0.0:13133
    path: /health
    check_collector_pipeline:
      enabled: true

  pprof:
    endpoint: 0.0.0.0:1888

  zpages:
    endpoint: 0.0.0.0:8889

service:
  extensions: [health_check, pprof, zpages]

  telemetry:
    logs:
      level: "info"
    metrics:
      readers:
        - pull:
            exporter:
              prometheus:
                host: 0.0.0.0
                port: 8888

  pipelines:
    traces:
      receivers: [otlp]
      processors: [memory_limiter, resourcedetection, probabilistic_sampler, batch]
      exporters: [otlp_grpc/tempo, debug]
